Repository parameter1/science-medicine-group-websites, pull requests merged in 2022-10, with the labels that each got.

#72 Enable Auth0 in staging env
  packages/global/components/auth0/access.marko
  packages/global/components/auth0/context.marko
  packages/global/components/layouts/content/default.marko
  sites/labpulse.com/config/navigation.js
Labels: staging

#68 Add newsletter pushdown & newsletterState middleware for auto expansion
  packages/global/browser/index.js
  packages/global/browser/site-newsletter-menu.vue
  packages/global/browser/site-newsletter-menu/signup.vue
  packages/global/browser/ssr.js
  packages/global/components/marko.json
  packages/global/components/site-header-c.marko
  packages/global/components/site-newsletter-menu.marko
  packages/global/middleware/newsletter-state.js
  packages/global/scss/components/_newsletter-pushdown.scss
  packages/global/scss/components/_site-navbar-c.scss
  packages/global/scss/core.scss
  sites/labpulse.com/config/newsletter.js
  sites/labpulse.com/server/routes/content.js
  sites/labpulse.com/server/routes/website-section.js
Labels: staging

#76 Add test support for init-only
  packages/global/components/document.marko
Labels: site: ALL

#78 Adjust ad breakpoints
  packages/global/components/wrappers/components/section-feed-block.marko
  packages/global/config/gam.js
  packages/global/scss/core.scss
Labels: site: ALL

#79 Adjust site menu, inline ad css
  packages/global/scss/core.scss
Labels: site: ALL

#80 Remove lazyload from home hero story
  packages/global/components/layouts/website-section/home.marko
Labels: site: ALL

#81 Increase z-index for menu
  packages/global/scss/core.scss
Labels: site: ALL

#83 Set image width + height attributes
  packages/global/components/layouts/website-section/home.marko
  packages/global/package.json
  sites/labpulse.com/package.json
  sites/scienceboard.net/package.json
  yarn.lock
Labels: site: ALL

#84 Set logo width + height values
  packages/global/components/site-footer.marko
  packages/global/components/site-header-c.marko
  sites/labpulse.com/config/site.js
Labels: site: ALL

#85 Upgrade deps
  packages/global/package.json
  sites/labpulse.com/package.json
  sites/scienceboard.net/package.json
  yarn.lock
Labels: site: ALL

#86 Disable newsletter dropdown
  packages/global/components/site-header-c.marko
Labels: site: ALL

#87 Add phoneNumber and organization to profile form
  packages/global/config/identity-x.js
Labels: site: ALL

#88 Upgrade deps
  packages/global/package.json
  sites/labpulse.com/package.json
  sites/scienceboard.net/package.json
  yarn.lock
Labels: site: ALL

#91 Remove updated date
  packages/global/components/layouts/content/default.marko
Labels: site: ALL

#92 Increase padding between stacked breadcrumb items
  packages/global/scss/core.scss
Labels: site: ALL

#93 Add Fira Sans-fallback font
  packages/global/scss/_variables.scss
Labels: site: ALL

#94 Update IdX user when submitting preferences
  packages/global/graphql/mutations/idx-user-update-receive-email.js
  packages/global/routes/braze.js
Labels: enhancement

#95 Remove ScrollMagic
  packages/global/components/document.marko
Labels: site: ALL

#99 Add git deployments for remaining sites
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
Labels: site: ALL

#105 Upgrade dependencies
  packages/global/package.json
  sites/auntminnie.com/package.json
  sites/auntminnieasia.com/package.json
  sites/auntminnieeurope.com/package.json
  sites/drbicuspid.com/package.json
  sites/labpulse.com/package.json
  sites/scienceboard.net/package.json
  yarn.lock
Labels: dependencies

#108 Customize IdentityX field labels
  packages/global/config/identity-x.js
Labels: staging

#107 Opt-in to newsletters on newsletter component submission
  packages/braze/hooks/index.js
  packages/braze/hooks/on-login-link-sent.js
  packages/braze/routes/preference-center.js
  packages/braze/utils.js
Labels: staging

#106 Updated flow for Auth0 DB users
  packages/auth0/README.md
  packages/auth0/after-callback.js
  packages/auth0/index.js
  packages/auth0/middleware/identity-x.js
  packages/auth0/middleware/index.js
  packages/auth0/package.json
  packages/auth0/templates/db-email-verification.marko
  packages/auth0/templates/index.js
  packages/global/package.json
  packages/global/start-server.js
  yarn.lock
Labels: staging

#109 Update newsletter signup color
  packages/global/scss/core.scss
Labels: site: ALL

#111 Update newsletter signup color
  packages/global/scss/core.scss
Labels: site: ALL
