Repository parameter1/science-medicine-group-websites, pull requests merged in 2022-08, with the labels that each got.

#8 Update menu primary item font size
  packages/global/scss/core.scss
Labels: site: ALL

#14 Update site footer
  docker-compose.yml
  packages/global/components/document.marko
  packages/global/components/marko.json
  packages/global/components/site-footer.marko
  packages/global/scss/components/_site-footer.scss
  packages/global/scss/core.scss
  sites/labpulse.com/config/navigation.js
  sites/scienceboard.net/config/navigation.js
Labels: site: ALL

#15 Add secondary nav items
  packages/global/scss/components/_site-navbar-c.scss
  sites/labpulse.com/config/navigation.js
Labels: site: labpulse.com

#18 Adjust top padding for right rail blocks
  packages/global/scss/core.scss
Labels: site: ALL

#19 Fix pagination in section feed wrapper & fix spreading of queryParams props
  packages/global/components/wrappers/section-feed.marko
Labels: bug

#26 Upgrade NewRelic package to latest node 10.x
  packages/global/package.json
  yarn.lock
Labels: bug
