Repository parameter1/science-medicine-group-websites, pull requests merged in 2022-11, with the labels that each got.

#114 Set default country code from MaxMind
  packages/global/package.json
  packages/global/start-server.js
  packages/global/templates/user/profile.marko
  packages/maxmind-geoip/env.js
  packages/maxmind-geoip/middleware.js
  packages/maxmind-geoip/package.json
  packages/zero-bounce/package.json
Labels: staging

#115 Update CTA text
  sites/labpulse.com/config/newsletter.js
Labels: staging

#116 Adjust opt-in behavior
  docker-compose.yml
  packages/auth0/package.json
  packages/braze/hooks/index.js
  packages/braze/hooks/on-authentication-success.js
  packages/braze/hooks/on-login-link-sent.js
  packages/braze/index.js
  packages/braze/package.json
  packages/braze/service.js
  packages/global/config/braze.js
  packages/global/package.json
  sites/auntminnie.com/package.json
  sites/auntminnieasia.com/package.json
  sites/auntminnieeurope.com/package.json
  sites/drbicuspid.com/package.json
  sites/labpulse.com/config/braze.js
  sites/labpulse.com/package.json
  sites/scienceboard.net/package.json
  yarn.lock
Labels: staging

#119 Auth0 resend email support
  docker-compose.yml
  packages/auth0/after-callback.js
  packages/auth0/browser/.eslintrc.js
  packages/auth0/browser/index.js
  packages/auth0/browser/send-verification-email.vue
  packages/auth0/index.js
  packages/auth0/middleware/index.js
  packages/auth0/package.json
  packages/auth0/service.js
  packages/auth0/templates/db-email-verification.marko
  packages/braze/service.js
  packages/global/browser/index.js
  packages/global/components/auth0/access.marko
  packages/global/components/auth0/context.marko
  packages/zero-bounce/service.js
  sites/auntminnie.com/config/auth0.js
  sites/auntminnieasia.com/config/auth0.js
  sites/auntminnieeurope.com/config/auth0.js
  sites/drbicuspid.com/config/auth0.js
  sites/labpulse.com/config/auth0.js
  sites/scienceboard.net/config/auth0.js
Labels: staging

#122 Upgrade dependencies
  packages/auth0/package.json
  packages/braze/package.json
  packages/global/package.json
  sites/auntminnie.com/package.json
  sites/auntminnieasia.com/package.json
  sites/auntminnieeurope.com/package.json
  sites/drbicuspid.com/package.json
  sites/labpulse.com/package.json
  sites/scienceboard.net/package.json
  yarn.lock
Labels: site: ALL

#123 Upgrade dependencies
  packages/auth0/package.json
  packages/global/package.json
  sites/auntminnie.com/package.json
  sites/auntminnieasia.com/package.json
  sites/auntminnieeurope.com/package.json
  sites/drbicuspid.com/package.json
  sites/labpulse.com/package.json
  sites/scienceboard.net/package.json
  yarn.lock
Labels: site: ALL

#124 Only show newsletter signup form for anonymous users
  packages/global/components/layouts/content/default.marko
Labels: site: ALL

#134 Fix flipped braze cookies
  packages/braze/middleware/set-id-cookies.js
Labels: bug
