Repository parameter1/science-medicine-group-websites, pull requests merged in 2024-05, with the labels that each got.

#531 Allow pass-through of brazeCustomAttributes on POST endpoint
  packages/braze/ingest/build-schema.js
  packages/braze/ingest/index.js
  packages/braze/ingest/set-braze-user-data.js
  packages/braze/utils.js
Labels: 🌐 site: ALL

#546 Include `brazeCustomAttributes` information in `braze/ingest` README.md
  packages/braze/ingest/README.md
Labels: documentation

#550 Add Podcasts to nav and promo card block to homepage, AuntMinnie
  sites/auntminnie.com/config/navigation.js
  sites/auntminnie.com/server/templates/index.marko
Labels: 🌐 site: auntminnie.com
