Repository parameter1/science-medicine-group-websites, pull requests merged in 2024-07, with the labels that each got.

#576 Remove upcoming feed and Submit a Conference from ‘Conferences’ website-section
  packages/global/components/layouts/website-section/upcoming-feed.marko
  packages/global/templates/website-section/conference.marko
Labels: 🌐 site: ALL

#577 Update Braze: default (AME-Daily) & unconfirmed group ID
  sites/auntminnieeurope.com/config/braze.js
Labels: 🌐 site: auntminnieeurope.com

#578 Include basic docs for GET and DELETE endpoints, Identity-X API
  packages/braze/ingest/README.md
Labels: documentation

#593 Always apply `last_email_activity_legacy` when utilizing trackUser, trackUser on login-link-sent
  packages/braze/hooks/on-login-link-sent.js
  packages/braze/service.js
Labels: 🌐 site: ALL

#594 "Single Opt In" registration flow
  packages/braze/hooks/on-login-link-sent.js
  packages/global/config/identity-x.js
Labels: 🌐 site: ALL

#599 Do not push cookie state changes for modal on pages or user routes
  packages/global/browser/newsletter-signup-modal-listener.vue
Labels: bug, 🌐 site: ALL

#596 Confirm user via incoming `braze_ext_id` on query string if not Identity-X verified
  packages/braze/middleware/confirm-user-via-query-string.js
  packages/global/start-server.js
Labels: 🌐 site: ALL
